# Permitir referencias circulares y overriding de beans
spring.main.allow-circular-references=true
spring.main.allow-bean-definition-overriding=true

# Configuracion del Servidor
server.port=8080

# Configuracion de la Base de Datos MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/sgsst?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=America/Lima
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuracion JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Configuracion de Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Configuracion de Seguridad
spring.security.user.name=admin
spring.security.user.password=admin123

# Configuracion de H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
