# Configuracion del Servidor
server.port=8080

# Permitir referencias circulares (solucion temporal)
spring.main.allow-circular-references=true

# Configuracion de la Base de Datos H2 (para desarrollo)
spring.datasource.url=jdbc:h2:mem:sgsst;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

# Configuracion JPA/Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# Configuracion de Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Configuracion de Seguridad
spring.security.user.name=admin
spring.security.user.password=admin123

# Configuracion de H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
